### ISSUE TITLE
Looking for the ARCv3 ISA manual

### ISSUE THREAD

**Issue by alexrp** [foss-for-synopsys-dwc-arc-processors/documentation#7]
Hi,

I'm posting here because I can't really find a better place to do so. Hope that's ok.

Over the past couple of weeks, I've been doing extensive porting of [Zig](https://ziglang.org) to just about every architecture supported by the combination of LLVM and Linux. ARCv2 is one of those. Fortunately, the ARCv2 ISA manual and ABI documentation was not too hard to find online.

Now, while LLVM doesn't seem to have ARCv3 support yet (and it's not clear to me if you're working on this), I'd still like to start porting some of the standard library bits so that they're in place when/if LLVM support materializes, or someone creates a [self-hosted backend](https://github.com/ziglang/zig/tree/master/src/arch).

The ABI documentation for ARCv3 is available on your GitHub. Unfortunately, I can't for the life of me find a publicly accessible ARCv3 ISA manual, despite the fact that all the toolchain bits are open source here. There is the "Downloads and Documentation" tab on [this page](https://www.synopsys.com/dw/ipdir.php?ds=arc-hs6x-processors), but best as I can tell, that page seems to require some kind of registration that's only possible for Synopsys customers.

Is it actually possible to get a copy of the ARCv3 ISA manual as a non-customer?

Thank you!

**Comment by abrodkin** [comment]
@alexrp thanks for your work on the Zig project. Let me check if I may share that document.

**Comment by abrodkin** [comment]
@alexrp just to let you know that we plan to make that document available soon. I don't have any dates now, but hopefully it won't take long, so please stay tuned. I'll update you once these documents get published.

**Comment by alexrp** [comment]
@abrodkin that's great news! Thanks for the taking to look into this. :slightly_smiling_face:

By the way, [I see that Synopsys contributed the ARCv2 target for LLVM in 2017](https://groups.google.com/g/llvm-dev/c/9srvMhZ8gpw/m/UEPJhuTOAAAJ). I don't suppose you know if there are any ongoing efforts to bring ARCv3 to LLVM?

**Comment by abrodkin** [comment]
> @abrodkin that's great news! Thanks for the taking to look into this. 🙂
> 
> By the way, [I see that Synopsys contributed the ARCv2 target for LLVM in 2017](https://groups.google.com/g/llvm-dev/c/9srvMhZ8gpw/m/UEPJhuTOAAAJ). I don't suppose you know if there are any ongoing efforts to bring ARCv3 to LLVM?

As far as I know, that was only a basic port for ARCv2 cores and so I doubt if it is usable for any serious development - it definitely requires quite a few improvements. As for ARCv3 port we're not working on that actively at this point. At the same time our proprietary MetaWare toolchain is based on Clang/LLVM and that toolchain supports all current ARC processors starting from ARCompact all the way to ARCv3 and even brand new RISC-V based ARC-V cores.

**Comment by abrodkin** [comment]
> @abrodkin that's great news! Thanks for the taking to look into this. 🙂
> 
> By the way, [I see that Synopsys contributed the ARCv2 target for LLVM in 2017](https://groups.google.com/g/llvm-dev/c/9srvMhZ8gpw/m/UEPJhuTOAAAJ). I don't suppose you know if there are any ongoing efforts to bring ARCv3 to LLVM?

As far as I know, that was only some very basic port for ARC cores and so I doubt if it is usable for any serious development - it definitely requires quite a few improvements. As for ARCv3 port we're not working on that actively at this point. At the same time our proprietary MetaWare toolchain is based on Clang/LLVM and that toolchain supports all current ARC processors starting from ARCompact all the way to ARCv3 and even brand new RISC-V based ARC-V cores. So depending on your use-case possibly that toolchain can be of some interest.

**Comment by abrodkin** [comment]
@alexrp please find Programmer's Reference Manuals (PRMs) for both flavors of ARCv3 processors:
* 32-bit, i.e. ARC HS5x: https://www.synopsys.com/dw/doc.php/iip/DWC_ARCv3HS5x/ARC_V3_ProgrammersReference_hs5x_public.pdf
* 64-bit, i.e. ARC HS6x: https://www.synopsys.com/dw/doc.php/iip/DWC_ARCv3HS6x/ARC_V3_ProgrammersReference_hs6x_public.pdf

You'll need to fill in a short form with your data, click "Submit" and you'll the document. Please let me know if it works for you.

**Comment by alexrp** [comment]
@abrodkin just downloaded them - thanks for taking the time to do this!
